apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
spec:
  project: spof-cluster
  sources:
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 6.1.0
      helm:
        releaseName: argo-cd
        valueFiles:
          - $values/values.yaml
    - repoURL: 'https://github.com/SP0Fs/argo-cd-k8s.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true